spring.application.name=shop

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/shop?CreateDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

server.port=8090

logging.level.org.springframework = info
logging.level.com.example.demo = debug

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#\uC800\uC7A5\uC2DC \uD30C\uC77C\uC5D0 \uB300\uD55C \uC81C\uD55C
#\uD30C\uC77C \uD55C\uAC1C\uB2F9 \uC6A9\uB7C9 \uC81C\uD55C
spring.servlet.multipart.max-file-size=20MB
#\uD55C\uBC88 \uC804\uC1A1\uC2DC \uC6A9\uB7C9 \uC81C\uD55C
spring.servlet.multipart.max-request-size=100MB

#\uC774\uBBF8\uC9C0 \uC800\uC7A5\uC704\uCE58 \uD30C\uC77C\uC800\uC7A5\uC2DC \uACBD\uB85C\uB97C \uBD88\uB7EC\uC640\uC11C \uC0AC\uC6A9
imgLocation=C:/ex/

#\uC774\uBBF8\uC9C0 \uC800\uC7A5\uC704\uCE58 #\uBCC0\uC218\uD654 \uBCFC\uB54C
uploadPath=file:///C:/ex

spring.jpa.properties.hibernate.default_batch_fetch_size = 100
